Repository TogetherHana/Backend, pull requests merged in 2024-07, with the labels that each got.

#37 승리팀 맞추기 이벤트 기능 구현
  togetherHana/src/main/java/com/togetherhana/auth/service/AuthService.java
  togetherHana/src/main/java/com/togetherhana/config/AsyncConfig.java
  togetherHana/src/main/java/com/togetherhana/config/JwtArgumentResolver.java
  togetherHana/src/main/java/com/togetherhana/config/SchedulerConfig.java
  togetherHana/src/main/java/com/togetherhana/event/predict/controller/EventController.java
  togetherHana/src/main/java/com/togetherhana/event/predict/dto/EventConcludeRequest.java
  togetherHana/src/main/java/com/togetherhana/event/predict/dto/EventGameCreateRequest.java
  togetherHana/src/main/java/com/togetherhana/event/predict/dto/EventGameInfoResponse.java
  togetherHana/src/main/java/com/togetherhana/event/predict/dto/PredictionRequest.java
  togetherHana/src/main/java/com/togetherhana/event/predict/entity/EventGame.java
  togetherHana/src/main/java/com/togetherhana/event/predict/entity/Prediction.java
  togetherHana/src/main/java/com/togetherhana/event/predict/repository/EventGameRepository.java
  togetherHana/src/main/java/com/togetherhana/event/predict/repository/PredictionRepository.java
  togetherHana/src/main/java/com/togetherhana/event/predict/service/EventGameConcludeEvent.java
  togetherHana/src/main/java/com/togetherhana/event/predict/service/EventGameListener.java
  togetherHana/src/main/java/com/togetherhana/event/predict/service/EventGameService.java
  togetherHana/src/main/java/com/togetherhana/event/predict/service/EventGameStartEvent.java
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/member/dto/SignUpRequest.java
  togetherHana/src/main/java/com/togetherhana/member/repository/DeviceInfoRepository.java
  togetherHana/src/main/java/com/togetherhana/member/repository/MemberRepository.java
  togetherHana/src/main/java/com/togetherhana/member/service/MemberService.java
  togetherHana/src/main/java/com/togetherhana/mileage/entity/Mileage.java
  togetherHana/src/main/java/com/togetherhana/transfer/dto/TransferResponse.java
Labels: feat🚀, fix🚧, refactor💎, 찰스🦊

#36 선착순 이벤트 기능 구현
  togetherHana/build.gradle
  togetherHana/src/main/java/com/togetherhana/TogetherHanaApplication.java
  togetherHana/src/main/java/com/togetherhana/config/RedisConfig.java
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/mileage/entity/Mileage.java
  togetherHana/src/main/java/com/togetherhana/mileage/repository/MileageRepository.java
  togetherHana/src/main/java/com/togetherhana/mileage/service/MileageService.java
  togetherHana/src/main/java/com/togetherhana/sportClub/controller/MyteamController.java
  togetherHana/src/main/java/com/togetherhana/systemEvent/controller/SystemEventController.java
  togetherHana/src/main/java/com/togetherhana/systemEvent/scheduler/SystemEventScheduler.java
  togetherHana/src/main/java/com/togetherhana/systemEvent/service/SystemEventService.java
Labels: feat🚀, 지후🐰

#39 선착순 이벤트 오류 수정
  togetherHana/src/main/java/com/togetherhana/auth/jwt/JwtTokenProvider.java
  togetherHana/src/main/java/com/togetherhana/event/controller/EventController.java
  togetherHana/src/main/java/com/togetherhana/event/firstcome/scheduler/FirstComeEventScheduler.java
  togetherHana/src/main/java/com/togetherhana/event/firstcome/service/FirstComeEventService.java
  togetherHana/src/main/java/com/togetherhana/mileage/service/MileageService.java
  togetherHana/src/main/java/com/togetherhana/systemEvent/controller/SystemEventController.java
Labels: fix🚧, 지후🐰

#41 게임 옵션 선택 api 수정
  togetherHana/src/main/java/com/togetherhana/game/controller/GameController.java
  togetherHana/src/main/java/com/togetherhana/game/service/GameService.java
Labels: fix🚧, 지후🐰

#43 계좌 입출금 시 알림발생 기능 추가
  togetherHana/Dockerfile
  togetherHana/docker-compose.yml
  togetherHana/src/main/java/com/togetherhana/sharingAccount/controller/SharingAccountController.java
  togetherHana/src/main/java/com/togetherhana/transfer/dto/DepositRequest.java
  togetherHana/src/main/java/com/togetherhana/transfer/service/TransferService.java
Labels: feat🚀, 찰스🦊

#45 매치 상세조회 응답을 수정
  togetherHana/src/main/java/com/togetherhana/game/dto/response/GameDetailResponseDto.java
  togetherHana/src/main/java/com/togetherhana/game/entity/Game.java
  togetherHana/src/main/java/com/togetherhana/game/repository/CustomGameRepository.java
  togetherHana/src/main/java/com/togetherhana/game/repository/CustomGameRepositoryImpl.java
  togetherHana/src/main/java/com/togetherhana/game/service/GameService.java
Labels: feat🚀, 지연😽

#47 게임 종료 시, 패배자에게 벌금요청 알림보내기 추가
  togetherHana/src/main/java/com/togetherhana/game/service/GameService.java
Labels: feat🚀
