Repository TogetherHana/Backend, pull requests merged in 2024-06, with the labels that each got.

#2 공통 에러 처리 & 공통 응답 response 정의
  togetherHana/src/main/java/com/togetherhana/base/BaseResponse.java
  togetherHana/src/main/java/com/togetherhana/exception/BaseException.java
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/exception/ExceptionControllerAdvice.java
Labels: feat🚀, 지연😽

#7 매치 생성 기능 구현
  togetherHana/.gradle/8.8/executionHistory/executionHistory.lock
  togetherHana/.gradle/8.8/fileHashes/fileHashes.lock
  togetherHana/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/game/controller/GameController.java
  togetherHana/src/main/java/com/togetherhana/game/dto/GameOptionDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/request/GameCreateRequestDto.java
  togetherHana/src/main/java/com/togetherhana/game/entity/Game.java
  togetherHana/src/main/java/com/togetherhana/game/entity/GameOption.java
  togetherHana/src/main/java/com/togetherhana/game/entity/GameParticipant.java
  togetherHana/src/main/java/com/togetherhana/game/repository/GameOptionRepository.java
  togetherHana/src/main/java/com/togetherhana/game/repository/GameRepository.java
  togetherHana/src/main/java/com/togetherhana/game/service/GameService.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/SharingAccountRepository.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/service/SharingAccountService.java
Labels: feat🚀, 지연😽

#10 sms인증, 계좌인증 기능 개발
  togetherHana/build.gradle
  togetherHana/src/main/java/com/togetherhana/auth/controller/AuthController.java
  togetherHana/src/main/java/com/togetherhana/auth/dto/AccountCertificationDto.java
  togetherHana/src/main/java/com/togetherhana/auth/dto/AccountCheckDto.java
  togetherHana/src/main/java/com/togetherhana/auth/dto/SmsCertificationDto.java
  togetherHana/src/main/java/com/togetherhana/auth/dto/SmsRequestDto.java
  togetherHana/src/main/java/com/togetherhana/auth/service/AuthService.java
  togetherHana/src/main/java/com/togetherhana/config/QueryDslConfig.java
  togetherHana/src/main/java/com/togetherhana/config/RedisConfig.java
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/sms/service/SmsService.java
Labels: feat🚀, 찰스🦊

#12 매치 투표 기능 구현
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/game/controller/GameController.java
  togetherHana/src/main/java/com/togetherhana/game/dto/request/OptionChoiceRequestDto.java
  togetherHana/src/main/java/com/togetherhana/game/entity/GameParticipant.java
  togetherHana/src/main/java/com/togetherhana/game/repository/GameParticipantRepository.java
  togetherHana/src/main/java/com/togetherhana/game/service/GameService.java
  togetherHana/src/main/java/com/togetherhana/mileage/controller/MileageController.java
  togetherHana/src/main/java/com/togetherhana/mileage/service/MileageService.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/SharingMemberRepository.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/service/SharingMemberService.java
Labels: feat🚀, 지연😽

#16 회원가입 및 로그인 JWT인증 , 닉네임 중복검사 API 구현
  .idea/compiler.xml
  .idea/gradle.xml
  togetherHana/.gradle/8.8/checksums/checksums.lock
  togetherHana/.gradle/8.8/checksums/md5-checksums.bin
  togetherHana/.gradle/8.8/checksums/sha1-checksums.bin
  togetherHana/.gradle/8.8/executionHistory/executionHistory.lock
  togetherHana/.gradle/8.8/fileHashes/fileHashes.lock
  togetherHana/.gradle/buildOutputCleanup/buildOutputCleanup.lock
  togetherHana/build.gradle
  togetherHana/src/main/java/com/togetherhana/auth/controller/AuthController.java
  togetherHana/src/main/java/com/togetherhana/auth/dto/JwtToken.java
  togetherHana/src/main/java/com/togetherhana/auth/jwt/JwtTokenExtractor.java
  togetherHana/src/main/java/com/togetherhana/auth/jwt/JwtTokenProvider.java
  togetherHana/src/main/java/com/togetherhana/auth/service/AuthService.java
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/member/controller/MemberController.java
  togetherHana/src/main/java/com/togetherhana/member/dto/SignUpRequest.java
  togetherHana/src/main/java/com/togetherhana/member/entity/DeviceInfo.java
  togetherHana/src/main/java/com/togetherhana/member/entity/Member.java
  togetherHana/src/main/java/com/togetherhana/member/repository/MemberRepository.java
  togetherHana/src/main/java/com/togetherhana/member/service/MemberService.java
  togetherHana/src/main/java/com/togetherhana/sportClub/controller/MyteamController.java
Labels: feat🚀, 지후🐰

#19 모임통장 도메인 관련 기능 개발
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/mileage/controller/MileageController.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/controller/SharingAccountController.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/dto/SharingAccountCreateRequest.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/dto/SharingAccountCreateResponse.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/dto/SharingAccountResponse.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/dto/SharingMemberResponse.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/entity/SharingAccount.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/CustomSharingAccountRepo.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/CustomSharingAccountRepoImpl.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/CustomSharingMemberRepository.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/CustomSharingMemberRepositoryImpl.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/SharingAccountRepository.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/SharingMemberRepository.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/service/SharingAccountService.java
  togetherHana/src/main/java/com/togetherhana/transfer/dto/TransferRequest.java
  togetherHana/src/main/java/com/togetherhana/transfer/dto/TransferResponse.java
  togetherHana/src/main/java/com/togetherhana/transfer/entity/TransactionType.java
  togetherHana/src/main/java/com/togetherhana/transfer/entity/TransferHistory.java
  togetherHana/src/main/java/com/togetherhana/transfer/repository/TransferRepository.java
  togetherHana/src/main/java/com/togetherhana/transfer/service/TransferService.java
  togetherHana/src/main/java/com/togetherhana/transferHistory/entity/TransferHistory.java
Labels: feat🚀, 찰스🦊

#23 매치 상세조회 기능 구현
  togetherHana/src/main/java/com/togetherhana/game/controller/GameController.java
  togetherHana/src/main/java/com/togetherhana/game/dto/GameOptionDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/request/GameCreateRequestDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/request/GameOptionRequestDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/response/GameDetailResponseDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/response/GameOptionDto.java
  togetherHana/src/main/java/com/togetherhana/game/repository/CustomGameRepository.java
  togetherHana/src/main/java/com/togetherhana/game/repository/CustomGameRepositoryImpl.java
  togetherHana/src/main/java/com/togetherhana/game/repository/GameRepository.java
  togetherHana/src/main/java/com/togetherhana/game/service/GameService.java
Labels: feat🚀, 지연😽

#26 Jwt에서 Member 추출하는 Resolver 구현
  togetherHana/src/main/java/com/togetherhana/auth/jwt/Auth.java
  togetherHana/src/main/java/com/togetherhana/auth/jwt/JwtTokenProvider.java
  togetherHana/src/main/java/com/togetherhana/config/JwtArgumentResolver.java
  togetherHana/src/main/java/com/togetherhana/config/WebMvcConfigure.java
  togetherHana/src/main/java/com/togetherhana/game/controller/GameController.java
  togetherHana/src/main/java/com/togetherhana/member/repository/MemberRepository.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/controller/SharingAccountController.java
Labels: feat🚀, refactor💎, 찰스🦊

#28 홈 화면 매치조회 기능 구현
  togetherHana/src/main/java/com/togetherhana/game/controller/GameController.java
  togetherHana/src/main/java/com/togetherhana/game/dto/request/GameCreateRequestDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/request/GameOptionRequestDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/request/OptionChoiceRequestDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/response/GameHistoryResponseDto.java
  togetherHana/src/main/java/com/togetherhana/game/dto/response/GameResultDto.java
  togetherHana/src/main/java/com/togetherhana/game/repository/CustomGameRepository.java
  togetherHana/src/main/java/com/togetherhana/game/repository/CustomGameRepositoryImpl.java
  togetherHana/src/main/java/com/togetherhana/game/service/GameService.java
Labels: feat🚀, 지연😽

#29 비동기 푸시 메세지 알림 기능 구현
  togetherHana/build.gradle
  togetherHana/src/main/java/com/togetherhana/config/AsyncConfig.java
  togetherHana/src/main/java/com/togetherhana/notification/event/NotificationEvent.java
  togetherHana/src/main/java/com/togetherhana/notification/fcm/FcmMessageSender.java
  togetherHana/src/main/java/com/togetherhana/notification/fcm/MessageSendManager.java
  togetherHana/src/main/java/com/togetherhana/notification/service/NotificationEventListener.java
  togetherHana/src/main/java/com/togetherhana/notification/service/NotificationService.java
Labels: feat🚀, 찰스🦊

#33 매치 상세 조회 수정
  togetherHana/src/main/java/com/togetherhana/game/entity/Game.java
  togetherHana/src/main/java/com/togetherhana/game/service/GameService.java
Labels: fix🚧, 지연😽

#34 FCM 푸시알림 기능 구현, 모임통장 초대장 생성 및 합류 기능구현
  togetherHana/src/main/java/com/togetherhana/exception/ErrorType.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/controller/InvitationController.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/controller/SharingAccountController.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/dto/ParticipateRequest.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/dto/SharingAccountResponse.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/dto/SharingMemberResponse.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/dto/TaxCollectRequest.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/CustomSharingMemberRepositoryImpl.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/repository/SharingMemberRepository.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/service/InvitationService.java
  togetherHana/src/main/java/com/togetherhana/sharingAccount/service/SharingAccountService.java
  togetherHana/src/main/java/com/togetherhana/transfer/dto/TransferResponse.java
  togetherHana/src/main/java/com/togetherhana/transfer/service/TransferService.java
Labels: feat🚀, fix🚧, 찰스🦊
